apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  CLUSTER_URL: mongodb+srv://milosz:uNlJ5MtGRbeWJS3z@mjtest80.er9zh.mongodb.net/?retryWrites=true&w=majority&appName=mjtest80
